#!/bin/bash

# run this from outside of mods folder

echo "<config version=\"0.20\">" > download.xml
echo " " >> download.xml
echo "  <!--This file should be generated by update.sh script-->" >> download.xml
echo "  <!--<file src==\"welcome.png=\" dest=\"welcome.png=\" size=\"1234\" md5=\"...\" />-->" >> download.xml
echo " " >> download.xml

for i in $( find  mods -type f); do
    size=$(ls -l $i |awk '{print $5}')
    md5=$(md5sum $i |awk '{print $1}') 
    echo  "  <file src=\"$i\" dest=\"$i\" size=\"${size}\" md5=\"${md5}\" />" >> download.xml
done
echo "</config>" >> download.xml
